service: my-react-app

provider:
  name: aws
  runtime: nodejs14.x
  profile: 237206178434_testing-platform-serverless-user
  stage: dev
  region: us-east-1

plugins:
  - serverless-s3-sync

custom:
  bucketName1: my-serverless-react-app-1
  bucketName2: my-serverless-react-app-2
  s3Sync:
    - bucketName: ${self:custom.bucketName1}
      localDir: ./build
    - bucketName: ${self:custom.bucketName2}
      localDir: ./build

resources:
  Resources:
    ReactAppBucket1:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName1}
        AccessControl: Private
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html

    ReactAppBucket2:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName2}
        AccessControl: Private
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html